@startuml
class TipoErro<<case>> {
  codigoArquivo: Int
  numeroLinha: Int
  conteudoLinha: String
  msg: String
  tipoErroImportacaoEnum: TipoErroImportacaoEnum
}

class "TipoErro "<<companion>> {
+existeTipoErro(a: Seq[TipoErro]): Boolean
+isError(a: TipoErro): Boolean
}

"TipoErro " <.. TipoErro : <<temUm>>

@enduml