@startuml

class Rotina<<T, #>> {
}
class Validador<<singleton>> {
}


class Etapa <<case>>{
    +Etapa(subEtapas: Seq[SubEtapa])
}

class SubEtapa <<case>>{
    +SubEtapa(regras: Seq[Regra])
}

class Regra

class Processadores
class MetaDados


@enduml